version: '3.8'

services:
  database:
    image: postgres:14.5
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '15432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data:cached
volumes:
  postgres-data:
